#!/usr/bin/env python3
"""
Airtable Structure Documentation Generator
"""

import os
import sys
import requests
from datetime import datetime
"""
# Configuration KORU
AIRTABLE_TOKEN = os.environ.get('AIRTABLE_TOKEN')
AIRTABLE_BASE_ID = os.environ.get('AIRTABLE_BASE_ID')
OUTPUT_FILE = 'database-structure.md'
"""

# Configuration AULAS
AIRTABLE_TOKEN = os.environ.get('AIRTABLE_TOKEN_AULAS')
AIRTABLE_BASE_ID = os.environ.get('AIRTABLE_BASE_ID_AULAS')
OUTPUT_FILE = 'database-structure-aulas.md'

def log(message, level="INFO"):
    """Simple logging function"""
    colors = {
        "INFO": "\033[94m",
        "SUCCESS": "\033[92m", 
        "ERROR": "\033[91m",
        "RESET": "\033[0m"
    }
    color = colors.get(level, colors["INFO"])
    print(f"{color}[{level}] {message}{colors['RESET']}")

def validate_config():
    """Validate configuration"""
    log("Validating configuration...")
    
    if not AIRTABLE_TOKEN:
        log("AIRTABLE_TOKEN is not set", "ERROR")
        return False
    
    if not AIRTABLE_BASE_ID:
        log("AIRTABLE_BASE_ID is not set", "ERROR")
        return False
    
    log(f"Base ID: {AIRTABLE_BASE_ID}", "SUCCESS")
    return True

def fetch_airtable_data():
    """Fetch data from Airtable API"""
    log("Fetching data from Airtable API...")
    
    url = f"https://api.airtable.com/v0/meta/bases/{AIRTABLE_BASE_ID}/tables"
    headers = {"Authorization": f"Bearer {AIRTABLE_TOKEN}"}
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            tables = data.get('tables', [])
            log(f"Found {len(tables)} tables", "SUCCESS")
            return tables
        else:
            log(f"API Error {response.status_code}: {response.text[:100]}", "ERROR")
            return None
            
    except Exception as e:
        log(f"Connection error: {e}", "ERROR")
        return None

def generate_documentation(tables):
    """Generate markdown documentation"""
    log("Generating documentation...")
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    # Start building markdown
    lines = []
    
    # Header
    lines.append("# 🗂️ Airtable Database Structure")
    lines.append("")
    lines.append(f"> **Last update**: {timestamp}")
    lines.append("> **Auto-generated** - Do not edit manually")
    lines.append("")
    
    # Summary
    total_fields = sum(len(table.get('fields', [])) for table in tables)
    lines.append("## 📊 Summary")
    lines.append("")
    lines.append(f"- **Tables**: {len(tables)}")
    lines.append(f"- **Fields**: {total_fields}")
    lines.append(f"- **Base ID**: `{AIRTABLE_BASE_ID}`")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Tables
    for table in tables:
        table_name = table.get('name', 'Unnamed')
        table_id = table.get('id', '')
        fields = table.get('fields', [])
        
        lines.append(f"## 🗃️ {table_name}")
        lines.append("")
        lines.append(f"*ID: `{table_id}`*")
        lines.append("")
        
        if fields:
            lines.append("| Field | Type | Options |")
            lines.append("|-------|------|---------|")
            
            for field in fields:
                field_name = field.get('name', 'Unnamed')
                field_type = field.get('type', 'unknown')
                field_id = field.get('id', '')
                
                # Get options for select fields
                options = ""
                if field_type in ['singleSelect', 'multipleSelects']:
                    choices = field.get('options', {}).get('choices', [])
                    if choices:
                        option_names = [choice.get('name', '') for choice in choices[:3]]
                        options = ", ".join([f"`{name}`" for name in option_names if name])
                        if len(choices) > 3:
                            options += f" (+{len(choices)-3} more)"
                
                lines.append(f"| **{field_name}**<br>`{field_id}` | `{field_type}` | {options} |")
        
        lines.append("")
        lines.append("---")
        lines.append("")
    
    # Footer
    lines.append("## 🔄 About")
    lines.append("")
    lines.append("This document is auto-generated by GitHub Actions.")
    lines.append("Updates daily at 8:00 AM UTC.")
    lines.append("")
    lines.append(f"*Generated: {timestamp}*")
    
    return "\n".join(lines)

def save_file(content, filename):
    """Save content to file"""
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        file_size = os.path.getsize(filename)
        log(f"File saved: {filename} ({file_size} bytes)", "SUCCESS")
        return True
        
    except Exception as e:
        log(f"Error saving file: {e}", "ERROR")
        return False

def main():
    """Main function"""
    print("\n" + "="*60)
    print("🚀 AIRTABLE DOCUMENTATION GENERATOR")
    print("="*60 + "\n")
    
    # 1. Validate
    if not validate_config():
        sys.exit(1)
    
    # 2. Fetch data
    tables = fetch_airtable_data()
    if tables is None:
        sys.exit(1)
    
    # 3. Generate
    documentation = generate_documentation(tables)
    
    # 4. Save
    if save_file(documentation, OUTPUT_FILE):
        log("\n✅ DOCUMENTATION GENERATED SUCCESSFULLY", "SUCCESS")
        log(f"📊 Tables: {len(tables)}", "INFO")
        log(f"📁 File: {OUTPUT_FILE}", "INFO")
        return 0
    else:
        log("\n❌ GENERATION FAILED", "ERROR")
        return 1

if __name__ == "__main__":
    sys.exit(main())



