#!/usr/bin/env python3
"""
Sync Airtable structure to Markdown documentation
"""

import os
import sys
import requests
from datetime import datetime

# Configuration from environment
AIRTABLE_TOKEN = os.getenv('AIRTABLE_TOKEN')
BASE_ID = os.getenv('AIRTABLE_BASE_ID')

def main():
    print("🚀 Starting Airtable documentation sync...")
    
    # Validate environment
    if not AIRTABLE_TOKEN:
        print("❌ ERROR: AIRTABLE_TOKEN environment variable not set")
        sys.exit(1)
    
    if not BASE_ID:
        print("❌ ERROR: AIRTABLE_BASE_ID environment variable not set")
        sys.exit(1)
    
    print(f"📋 Base ID: {BASE_ID}")
    print(f"🔐 Token: {'*' * 10}{AIRTABLE_TOKEN[-5:] if AIRTABLE_TOKEN else 'NONE'}")
    
    # Fetch Airtable metadata
    print("\n📡 Fetching Airtable metadata...")
    url = f"https://api.airtable.com/v0/meta/bases/{BASE_ID}/tables"
    headers = {"Authorization": f"Bearer {AIRTABLE_TOKEN}"}
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        
        if response.status_code != 200:
            print(f"❌ API Error {response.status_code}: {response.text[:100]}")
            sys.exit(1)
        
        data = response.json()
        tables = data.get('tables', [])
        
        if not tables:
            print("⚠️ No tables found in the base")
            tables = []
            
    except Exception as e:
        print(f"❌ Error fetching data: {e}")
        sys.exit(1)
    
    # Generate Markdown
    print(f"\n📝 Generating documentation for {len(tables)} tables...")
    
    update_time = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    markdown = f"""# 🗂️ Airtable Database Structure

> Last automated update: {update_time}
> 
> ⚠️ **This file is auto-generated. Do not edit manually.**

## 📊 Overview

- **Total tables**: {len(tables)}
- **Base ID**: `{BASE_ID}`
- **Auto-update**: Daily at 8:00 AM UTC

---

"""
    
    # Process each table
    for table in tables:
        table_name = table.get('name', 'Unnamed Table')
        table_id = table.get('id', '')
        fields = table.get('fields', [])
        
        markdown += f"## 📋 {table_name}\n\n"
        markdown += f"*Table ID: `{table_id}`*\n\n"
        
        if not fields:
            markdown += "*No fields in this table*\n\n"
        else:
            markdown += "| Field | Type | Options |\n"
            markdown += "|-------|------|---------|\n"
            
            for field in fields:
                field_name = field.get('name', 'Unnamed Field')
                field_type = field.get('type', 'unknown')
                field_id = field.get('id', '')
                
                # Get options for select fields
                options = ""
                if field_type in ['singleSelect', 'multipleSelects']:
                    choices = field.get('options', {}).get('choices', [])
                    if choices:
                        option_names = [choice.get('name', '') for choice in choices[:3]]
                        options = ", ".join([f"`{name}`" for name in option_names if name])
                        if len(choices) > 3:
                            options += f" (+{len(choices)-3} more)"
                
                markdown += f"| **{field_name}**<br>`{field_id}` | `{field_type}` | {options} |\n"
        
        markdown += "\n---\n\n"
    
    # Add footer
    markdown += f"""
## 🔄 About This Documentation

This file is automatically generated by GitHub Actions.
- **Schedule**: Daily at 8:00 AM UTC
- **Trigger**: Manual runs also available
- **Source**: Airtable API

*Generated on {update_time}*
"""
    
    # Save to file
    print("\n💾 Saving to database-structure.md...")
    try:
        with open('database-structure.md', 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        # Verify
        with open('database-structure.md', 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        print(f"✅ Successfully saved {len(lines)} lines")
        print(f"📄 First 3 lines:")
        for i in range(min(3, len(lines))):
            print(f"   {lines[i].rstrip()}")
        
    except Exception as e:
        print(f"❌ Error saving file: {e}")
        sys.exit(1)
    
    print("\n🎉 Documentation sync completed successfully!")
    return 0

if __name__ == '__main__':
    sys.exit(main())
